# Generated by Django 5.1.4 on 2025-01-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=222)),
                ('address', models.CharField(max_length=222)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.job')),
            ],
        ),
    ]
